language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn DskipTests clean install" ;fi
env:
  global:
  - secure: J1r5nTEnPD+mTLU26cIu+gAPVSgGutb85gjBAt2Dn6q+xKlSX8vlGFi95F0mdv7j5DLA4Due1dVhvPRN3YI93giBgUmgqX3MGU3vzQEV8gI5R9UD0eAniliB7vOZQ7gZcy/FOn2gC+JiVdu/+JxkbXEqMKh66SoEefkB9dVGfYTKYRuVxdyRItt8SAr17ngnT1d/8fFasYFsVBk9FRK5KYRDlR3hr2RU7uAKahATFoLWWMYvW6wWIjmwIszS2D5SXbNQ8ijcwRzA3m5wVLEy6VPsukAIn0AcQ/jAOIzhtiBEn9LeLMwYghD5xZIjNn5EFV/kIR49qDnIG+MnkK7z+sJpMnv1wkNLtJYmZMicpF+g30oANdwGhq5mhrrwPn9bAIO1wzZWDJE4ecL6c9Coua+dYgeYd9jImak5GJpTIDHmMeLgE8OU4Pda9DTKLteBkLg5PN7bPahuTpj36udpkalBDeKUMxi30nsnj0hzVfKA2JkQMrIWujEcCKoTP71Bp+m7UCPCzkVsNJihJrfj9Vfp3qBIkzSSHtQUKyaKc75boEXFH/YmUmfTwVFag96Ym2kiBU9YV3DFPO07d30B3qbrmbfAU1NO7KZpQIkZCirKfhm1PZHK0+/hHSILLZ9yWa9r14ZZ8UW2arS0fmqJ46WlvATMbyRU4qckxk8iCIU=
  - secure: N6EY5EjR6QpUJmc9qAJthrkRo8g/fh1qTcNLfzQBp6t79tGbcwbEyvOav0Yg6BUgRqjSJM0MfnzFCMrVg/b86BPkjo71ZhcFcDAsHrjtiPrGJxrzWkExXe0kO9QMFk9JltKQhV5s8RXQBhfWCFSyFEgSmwBIUaHnyhAW5cQX53ckYlxB1fyw96t1KrAEzWNqqJzsuG9187h4Vh2vmFUEnFu17BnACvcbVNzbrAWwdk4PhA+VrfLu3FfNhRhcgKtDauiCUxHQlgnHqy2tkpvkeboc/4ZWll2C7YOi005Xx/ufTXQcbRUD66NwNfhcmWIS/tCUOwUTkKgmTASQ6ubh//zE2+/ec6JTjKudz34NLWGShxagEqYM87Bfya0msGGoVDAiATgx4BYnBi7hWql1WZciLx0VBQDVwOpuxFrhiL9/SETlj0L/IBWmI6D+MFnydcuydoGhVUDtKw66AoWQS55lmyybQ+M3tw+GcaMkOq4YRPF7y91bPneAs6vmsT/8xN5Ln927gOQO739ShfpSWvX2LjKNwnItz21VT4HRld2lFbVBu03oGk9FS5ldkmZ/mQn0c8pv/QlDAfBgSeoWdEzgRY5rloE3pQurYeBU+i/e8opxrsZxzH7pzpwlmNbo6fgeyDBhxnlABJgPB85XprLoQQQADEn69bcckUzIy1g=
